security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: user_provider
            form_login:
                login_path: app_user_authentication_authenticate_user
                check_path: app_user_authentication_authenticate_user
            logout:
                path: /user/authentication/logout

    access_control:
        - { path: ^/user/authentication/login, roles: PUBLIC_ACCESS }
        - { path: ^/user/register, roles: PUBLIC_ACCESS }
        - { path: ^/ , roles: ROLE_USER }
